<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="58" total="97" passed="39">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="259777" started-at="2023-05-30T13:14:33Z" finished-at="2023-05-30T13:18:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="259777" started-at="2023-05-30T13:14:33Z" finished-at="2023-05-30T13:18:53Z">
      <class name="com.twc.ios.app.testcases.AndroidUSAPrivacyTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="beforeClass" is-config="true" duration-ms="30269" started-at="2023-05-30T18:44:33Z" finished-at="2023-05-30T18:45:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="preConditionsTest_for_USA()[pri:0, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="preConditionsTest_for_USA" duration-ms="41680" started-at="2023-05-30T18:45:04Z" finished-at="2023-05-30T18:45:45Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.functions.Functions.launchtheAndroidApp(Functions.java:551)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.preConditionsTest_for_USA(AndroidUSAPrivacyTest.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preConditionsTest_for_USA -->
        <test-method status="FAIL" signature="verify_enabling_Privacy_optin_for_USA()[pri:10, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_enabling_Privacy_optin_for_USA" duration-ms="10" started-at="2023-05-30T18:45:45Z" finished-at="2023-05-30T18:45:45Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_enabling_Privacy_optin_for_USA(AndroidUSAPrivacyTest.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_enabling_Privacy_optin_for_USA -->
        <test-method status="PASS" signature="navigate_To_Feed_Cards_when_Privacy_optin_for_USA()[pri:11, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="navigate_To_Feed_Cards_when_Privacy_optin_for_USA" duration-ms="5085" started-at="2023-05-30T18:45:45Z" finished-at="2023-05-30T18:45:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_To_Feed_Cards_when_Privacy_optin_for_USA -->
        <test-method status="FAIL" signature="validate_NextGen_IM_Adcall_sod_val_privacy_optin_for_USA()[pri:19, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_Adcall_sod_val_privacy_optin_for_USA" duration-ms="45" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_Adcall_sod_val_privacy_optin_for_USA(AndroidUSAPrivacyTest.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_Adcall_sod_val_privacy_optin_for_USA -->
        <test-method status="FAIL" signature="verify_Daily_details_call_sod_val_privacy_optin_for_USA()[pri:21, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_Daily_details_call_sod_val_privacy_optin_for_USA" duration-ms="18" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2F10day not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2F10day not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_Daily_details_call_sod_val_privacy_optin_for_USA(AndroidUSAPrivacyTest.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Daily_details_call_sod_val_privacy_optin_for_USA -->
        <test-method status="FAIL" signature="Verify_Amazon_Call_for_USA()[pri:26, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Amazon_Call_for_USA" duration-ms="20" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Amazon :API Call expected to present but it not exists]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Amazon :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verify_Amazon_aax_call(Utils.java:13513)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.Verify_Amazon_Call_for_USA(AndroidUSAPrivacyTest.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Amazon_Call_for_USA -->
        <test-method status="FAIL" signature="Verify_Lotame_call_privacy_optin_for_USA()[pri:38, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Lotame_call_privacy_optin_for_USA" duration-ms="18" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lotame :API Call expected to present but it not exists]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lotame :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verifyAPICal(Utils.java:1713)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.Verify_Lotame_call_privacy_optin_for_USA(AndroidUSAPrivacyTest.java:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Lotame_call_privacy_optin_for_USA -->
        <test-method status="PASS" signature="Verify_LocationWFXTriggers_Call_privacy_optin_for_USA()[pri:39, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_LocationWFXTriggers_Call_privacy_optin_for_USA" duration-ms="17" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LocationWFXTriggers_Call_privacy_optin_for_USA -->
        <test-method status="FAIL" signature="Verify_WFXTriggers_Call_privacy_optin_for_USA()[pri:40, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_WFXTriggers_Call_privacy_optin_for_USA" duration-ms="16" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[WFXTrigger :API Call expected to present but it not exists]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: WFXTrigger :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verifyAPICal(Utils.java:1713)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.Verify_WFXTriggers_Call_privacy_optin_for_USA(AndroidUSAPrivacyTest.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_WFXTriggers_Call_privacy_optin_for_USA -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_rdp_val_privacy_optin_for_USA()[pri:42, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_rdp_val_privacy_optin_for_USA" duration-ms="14" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_rdp_val_privacy_optin_for_USA(AndroidUSAPrivacyTest.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_rdp_val_privacy_optin_for_USA -->
        <test-method status="FAIL" signature="Verify_Criteo_SDK_inapp_v2_Call()[pri:51, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_inapp_v2_Call" duration-ms="21" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[bidder.criteo.com/inapp/v2 :API Call expected to present but it not exists]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: bidder.criteo.com/inapp/v2 :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verifyCriteo_inapp_v2_Call(Utils.java:11160)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.Verify_Criteo_SDK_inapp_v2_Call(AndroidUSAPrivacyTest.java:370)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_inapp_v2_Call -->
        <test-method status="FAIL" signature="Verify_Criteo_SDK_config_app_Call()[pri:52, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_config_app_Call" duration-ms="19" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[bidder.criteo.com/config/app :API Call expected to present but it not exists]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: bidder.criteo.com/config/app :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verifyCriteo_config_app_Call(Utils.java:11227)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.Verify_Criteo_SDK_config_app_Call(AndroidUSAPrivacyTest.java:383)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_config_app_Call -->
        <test-method status="FAIL" signature="derive_VideoCall_IU_when_Privacy_optin_for_USA()[pri:75, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="derive_VideoCall_IU_when_Privacy_optin_for_USA" duration-ms="5" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.derive_VideoCall_IU_when_Privacy_optin_for_USA(AndroidUSAPrivacyTest.java:394)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- derive_VideoCall_IU_when_Privacy_optin_for_USA -->
        <test-method status="FAIL" signature="verify_PrerollAd_call_sod_val_privacy_optin_for_USA()[pri:76, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_PrerollAd_call_sod_val_privacy_optin_for_USA" duration-ms="17" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_PrerollAd_call_sod_val_privacy_optin_for_USA(AndroidUSAPrivacyTest.java:415)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_PrerollAd_call_sod_val_privacy_optin_for_USA -->
        <test-method status="FAIL" signature="validate_PrerollVideo_call_rdp_val_privacy_optin_for_USA()[pri:77, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_PrerollVideo_call_rdp_val_privacy_optin_for_USA" duration-ms="16" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_PrerollVideo_call_rdp_val_privacy_optin_for_USA(AndroidUSAPrivacyTest.java:426)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_PrerollVideo_call_rdp_val_privacy_optin_for_USA -->
        <test-method status="FAIL" signature="verify_enabling_Privacy_optout_for_USA()[pri:101, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_enabling_Privacy_optout_for_USA" duration-ms="5" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:51Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_enabling_Privacy_optout_for_USA(AndroidUSAPrivacyTest.java:436)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_enabling_Privacy_optout_for_USA -->
        <test-method status="PASS" signature="navigate_To_Feed_Cards_when_Privacy_optout_for_USA()[pri:102, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="navigate_To_Feed_Cards_when_Privacy_optout_for_USA" duration-ms="5042" started-at="2023-05-30T18:45:51Z" finished-at="2023-05-30T18:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_To_Feed_Cards_when_Privacy_optout_for_USA -->
        <test-method status="FAIL" signature="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA()[pri:105, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA" duration-ms="16" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA(AndroidUSAPrivacyTest.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA -->
        <test-method status="FAIL" signature="verify_Daily_details_call_sod_val_privacy_optout_for_USA()[pri:107, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_Daily_details_call_sod_val_privacy_optout_for_USA" duration-ms="11" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2F10day not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fdetails%2F10day not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_Daily_details_call_sod_val_privacy_optout_for_USA(AndroidUSAPrivacyTest.java:524)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_Daily_details_call_sod_val_privacy_optout_for_USA -->
        <test-method status="PASS" signature="Verify_Amazon_Call_privacy_optout_for_USA()[pri:111, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Amazon_Call_privacy_optout_for_USA" duration-ms="13" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Amazon_Call_privacy_optout_for_USA -->
        <test-method status="PASS" signature="Verify_Lotame_Call_privacy_optout_for_USA()[pri:131, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Lotame_Call_privacy_optout_for_USA" duration-ms="13" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Lotame_Call_privacy_optout_for_USA -->
        <test-method status="PASS" signature="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA()[pri:132, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA" duration-ms="12" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LocationWFXTriggers_Call_privacy_optout_for_USA -->
        <test-method status="PASS" signature="Verify_WFXTriggers_Call_privacy_optout_for_USA()[pri:133, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_WFXTriggers_Call_privacy_optout_for_USA" duration-ms="10" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_WFXTriggers_Call_privacy_optout_for_USA -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA()[pri:135, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA" duration-ms="14" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA(AndroidUSAPrivacyTest.java:591)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA()[pri:140, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA" duration-ms="12" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA()[pri:141, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA" duration-ms="9" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA -->
        <test-method status="FAIL" signature="derive_VideoCall_IU_when_Privacy_optout_for_USA()[pri:175, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="derive_VideoCall_IU_when_Privacy_optout_for_USA" duration-ms="3" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.derive_VideoCall_IU_when_Privacy_optout_for_USA(AndroidUSAPrivacyTest.java:626)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- derive_VideoCall_IU_when_Privacy_optout_for_USA -->
        <test-method status="FAIL" signature="verify_PrerollAd_call_sod_val_privacy_optout_for_USA()[pri:176, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_PrerollAd_call_sod_val_privacy_optout_for_USA" duration-ms="15" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_PrerollAd_call_sod_val_privacy_optout_for_USA(AndroidUSAPrivacyTest.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_PrerollAd_call_sod_val_privacy_optout_for_USA -->
        <test-method status="FAIL" signature="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA()[pri:177, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA" duration-ms="10" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:45:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA(AndroidUSAPrivacyTest.java:658)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA -->
        <test-method status="FAIL" signature="enable_PreConfiguration_for_USA_To_LGPD_Travel_Scenario()[pri:200, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="enable_PreConfiguration_for_USA_To_LGPD_Travel_Scenario" duration-ms="30210" started-at="2023-05-30T18:45:56Z" finished-at="2023-05-30T18:46:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.functions.Functions.put_Background_launchAndroid(Functions.java:2008)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.enable_PreConfiguration_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:689)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enable_PreConfiguration_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="PASS" signature="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:201, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="5034" started-at="2023-05-30T18:46:26Z" finished-at="2023-05-30T18:46:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:210, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="13" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:733)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Amazon_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:213, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Amazon_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="11" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Amazon_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Lotame_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:231, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Lotame_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="14" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Lotame_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:232, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="14" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:235, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:802)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:241, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="13" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:815)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:250, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="13" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:251, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:275, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="3" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:852)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:276, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="12" started-at="2023-05-30T18:46:31Z" finished-at="2023-05-30T18:46:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:277, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="16" started-at="2023-05-30T18:46:32Z" finished-at="2023-05-30T18:46:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:885)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_Video_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario()[pri:278, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_Video_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario" duration-ms="15" started-at="2023-05-30T18:46:32Z" finished-at="2023-05-30T18:46:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_Video_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario(AndroidUSAPrivacyTest.java:896)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Video_call_npa_val_privacy_optout_for_USA_To_LGPD_Travel_Scenario -->
        <test-method status="FAIL" signature="enable_PreConfiguration_for_USA_To_GDPR_Travel_Scenario()[pri:300, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="enable_PreConfiguration_for_USA_To_GDPR_Travel_Scenario" duration-ms="30179" started-at="2023-05-30T18:46:32Z" finished-at="2023-05-30T18:47:02Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.functions.Functions.put_Background_launchAndroid(Functions.java:2008)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.enable_PreConfiguration_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:925)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enable_PreConfiguration_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="PASS" signature="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:301, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="5032" started-at="2023-05-30T18:47:02Z" finished-at="2023-05-30T18:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:310, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:968)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Amazon_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:313, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Amazon_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Amazon_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Lotame_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:331, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Lotame_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="8" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Lotame_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:332, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="12" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:335, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:1037)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:341, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="12" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:1048)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:350, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:351, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="11" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:375, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="4" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.derive_VideoCall_IU_when_Privacy_optout_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:1085)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- derive_VideoCall_IU_when_Privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:376, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:1107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_Video_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:377, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_Video_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="8" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_Video_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:1118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Video_call_npa_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario()[pri:378, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario(AndroidUSAPrivacyTest.java:1130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_GDPR_Travel_Scenario -->
        <test-method status="FAIL" signature="enable_PreConfiguration_for_USA_To_SERBIA_Travel_Scenario()[pri:400, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="enable_PreConfiguration_for_USA_To_SERBIA_Travel_Scenario" duration-ms="30171" started-at="2023-05-30T18:47:07Z" finished-at="2023-05-30T18:47:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.functions.Functions.put_Background_launchAndroid(Functions.java:2008)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.enable_PreConfiguration_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enable_PreConfiguration_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="PASS" signature="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:401, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="5032" started-at="2023-05-30T18:47:37Z" finished-at="2023-05-30T18:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:410, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="14" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Amazon_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:413, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Amazon_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="16" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Amazon_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Lotame_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:431, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Lotame_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="15" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Lotame_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:432, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="17" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:435, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="14" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:441, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="14" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:450, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="13" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:451, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:475, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="3" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.derive_VideoCall_IU_when_Privacy_optout_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- derive_VideoCall_IU_when_Privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:476, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="29" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_Video_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:477, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_Video_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="8" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_Video_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Video_call_npa_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario()[pri:478, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario" duration-ms="7" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:47:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario(AndroidUSAPrivacyTest.java:1365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_SERBIA_Travel_Scenario -->
        <test-method status="FAIL" signature="enable_PreConfiguration_for_USA_To_LATAMCO_Travel_Scenario()[pri:500, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="enable_PreConfiguration_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="30154" started-at="2023-05-30T18:47:42Z" finished-at="2023-05-30T18:48:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.functions.Functions.put_Background_launchAndroid(Functions.java:2008)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.enable_PreConfiguration_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1394)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enable_PreConfiguration_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="PASS" signature="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:501, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="5035" started-at="2023-05-30T18:48:12Z" finished-at="2023-05-30T18:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:510, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1437)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Amazon_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:513, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Amazon_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Amazon_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Lotame_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:531, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Lotame_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="7" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Lotame_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:532, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="7" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:535, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="12" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1505)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:541, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="11" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1516)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:550, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:551, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="8" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:575, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="5" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- derive_VideoCall_IU_when_Privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:576, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="11" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_Video_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:577, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_Video_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_npa_val_in_gampad_url(Utils.java:3452)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_Video_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1586)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Video_call_npa_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario()[pri:578, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario(AndroidUSAPrivacyTest.java:1598)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_LATAMCO_Travel_Scenario -->
        <test-method status="FAIL" signature="enable_PreConfiguration_for_USA_To_USACCPA_Travel_Scenario()[pri:800, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="enable_PreConfiguration_for_USA_To_USACCPA_Travel_Scenario" duration-ms="30156" started-at="2023-05-30T18:48:18Z" finished-at="2023-05-30T18:48:48Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.functions.Functions.put_Background_launchAndroid(Functions.java:2008)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.enable_PreConfiguration_for_USA_To_USACCPA_Travel_Scenario(AndroidUSAPrivacyTest.java:1629)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enable_PreConfiguration_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="PASS" signature="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:801, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="5032" started-at="2023-05-30T18:48:48Z" finished-at="2023-05-30T18:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_To_Feed_Cards_when_Privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:810, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario(AndroidUSAPrivacyTest.java:1672)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_Adcall_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Amazon_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:813, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Amazon_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Amazon_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Lotame_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:831, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Lotame_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="9" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Lotame_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:832, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="12" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_LocationWFXTriggers_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:835, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: iu=%2F7646%2Fapp_android_us%2Fdb_display%2Fhome_screen%2Fmarquee ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario(AndroidUSAPrivacyTest.java:1741)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_NextGen_IM_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:850, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="8" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_inapp_v2_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="PASS" signature="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:851, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Criteo_SDK_config_app_Call_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="FAIL" signature="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:875, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="derive_VideoCall_IU_when_Privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="4" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.derive_VideoCall_IU_when_Privacy_optout_for_USA_To_USACCPA_Travel_Scenario(AndroidUSAPrivacyTest.java:1778)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- derive_VideoCall_IU_when_Privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="FAIL" signature="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:876, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ad Call :null not found in charles session, hence Custom Parameter: sod validation skipped
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_custom_param_val_of_gampad(Utils.java:10117)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario(AndroidUSAPrivacyTest.java:1800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_PrerollAd_call_sod_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="FAIL" signature="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario()[pri:878, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario" duration-ms="10" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null ad call is not present]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null ad call is not present
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.validate_rdp_val_in_gampad_url(Utils.java:3356)
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario(AndroidUSAPrivacyTest.java:1813)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_PrerollVideo_call_rdp_val_privacy_optout_for_USA_To_USACCPA_Travel_Scenario -->
        <test-method status="FAIL" signature="afterClass()[pri:0, instance:com.twc.ios.app.testcases.AndroidUSAPrivacyTest@5ee34b1b]" name="afterClass" is-config="true" duration-ms="0" started-at="2023-05-30T18:48:53Z" finished-at="2023-05-30T18:48:53Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.twc.ios.app.testcases.AndroidUSAPrivacyTest.afterClass(AndroidUSAPrivacyTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.twc.ios.app.testcases.AndroidUSAPrivacyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
