<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Aswinikumars-MacBook-Pro.local" name="com.twc.ios.app.testcases.AndroidRegressionTest" tests="17" failures="3" timestamp="22 Nov 2022 15:45:58 GMT" time="1047.724" errors="0">
  <testcase name="Verify_Lotame_Call_When_Premium_Subscription_Monthly_Enabled" time="0.392" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_WFXTriggers_Call_When_Premium_Subscription_Monthly_Enabled" time="0.041" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_LocationWFXTriggers_Call_When_Premium_Subscription_Monthly_Expired" time="0.030" classname="com.twc.ios.app.testcases.AndroidRegressionTest">
    <failure type="java.lang.AssertionError" message="LocationWFX :API Call expected to present but it not exists">
      <![CDATA[java.lang.AssertionError: LocationWFX :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verifyAPICal(Utils.java:1670)
	at com.twc.ios.app.testcases.AndroidRegressionTest.Verify_LocationWFXTriggers_Call_When_Premium_Subscription_Monthly_Expired(AndroidRegressionTest.java:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_LocationWFXTriggers_Call_When_Premium_Subscription_Monthly_Expired -->
  <testcase name="Verify_LocationWFXTriggers_Call_When_Premium_Subscription_Monthly_Enabled" time="0.049" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Amazon_Call_When_Premium_Subscription_Monthly_Expired" time="0.028" classname="com.twc.ios.app.testcases.AndroidRegressionTest">
    <failure type="java.lang.AssertionError" message="Amazon :API Call expected to present but it not exists">
      <![CDATA[java.lang.AssertionError: Amazon :API Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verify_Amazon_aax_call(Utils.java:12575)
	at com.twc.ios.app.testcases.AndroidRegressionTest.Verify_Amazon_Call_When_Premium_Subscription_Monthly_Expired(AndroidRegressionTest.java:417)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_Amazon_Call_When_Premium_Subscription_Monthly_Expired -->
  <testcase name="Verify_Criteo_SDK_inapp_v2_Call_When_Premium_Subscription_Monthly_Expired" time="0.029" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_WFXTriggers_Call_When_Premium_Subscription_Monthly_Expired" time="0.030" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="enablePremiumSubsription" time="343.799" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Lotame_Call_When_Premium_Subscription_Monthly_Expired" time="0.202" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Gampad_call_When_Premium_Subscription_Monthly_Expired" time="0.029" classname="com.twc.ios.app.testcases.AndroidRegressionTest">
    <failure type="java.lang.AssertionError" message="Gampad :ad Call expected to present but it not exists">
      <![CDATA[java.lang.AssertionError: Gampad :ad Call expected to present but it not exists
	at org.testng.Assert.fail(Assert.java:94)
	at com.twc.ios.app.general.Utils.verify_Gampad_adcall(Utils.java:12530)
	at com.twc.ios.app.testcases.AndroidRegressionTest.Verify_Gampad_call_When_Premium_Subscription_Monthly_Expired(AndroidRegressionTest.java:458)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_Gampad_call_When_Premium_Subscription_Monthly_Expired -->
  <testcase name="beforeTest" time="69.107" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Amazon_Call_When_Premium_Subscription_Monthly_Enabled" time="0.034" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Criteo_SDK_config_app_Call_When_Premium_Subscription_Monthly_Expired" time="0.021" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Criteo_SDK_inapp_v2_Call_When_Premium_Subscription_Monthly_Enabled" time="0.049" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="checkPremiumSubsriptionMonthlyExpiry" time="633.811" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Criteo_SDK_config_app_Call_When_Premium_Subscription_Monthly_Enabled" time="0.036" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
  <testcase name="Verify_Gampad_call_When_Premium_Subscription_Monthly_Enabled" time="0.037" classname="com.twc.ios.app.testcases.AndroidRegressionTest"/>
</testsuite> <!-- com.twc.ios.app.testcases.AndroidRegressionTest -->
